//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "task_kind")]
pub enum TaskKind {
    /// For "Bar" tasks, the worker should make a GET request to https://www.whattimeisitrightnow.com/ and print the response's status code
    #[sea_orm(string_value = "bar")]
    Bar,
    /// For "Baz" tasks, the worker should generate a random number, N (0 to 343
    /// inclusive), and print "Baz {N}"
    #[sea_orm(string_value = "baz")]
    Baz,
    /// For "Foo" tasks, the worker should sleep for 3 seconds, and then print
    /// "Foo {task_id}".
    #[sea_orm(string_value = "foo")]
    Foo,
}
